nome=input('Qual o seu nome? ')
print('Olá',nome,'!!!')
idade=input('Quantos anos você tem? ')
peso=input('Quanto você pesa? ')
print(nome+', ' 'Suas informações são:')
print('Idade:',idade+',',peso+'kg''.')
print('Até mais!!!')
